# Generated by Django 4.2.16 on 2024-09-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
