# Generated by Django 4.2.16 on 2024-09-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('name', models.CharField(choices=[('Будни', 'Weekdays'), ('Выходные', 'Weekends'), ('Понедельник', 'Monday'), ('Вторник', 'Tuesday'), ('Среда', 'Wednesday'), ('Четверг', 'Thursday'), ('Пятница', 'Friday'), ('Суббота', 'Saturday'), ('Воскресенье', 'Sunday')], max_length=15, primary_key=True, serialize=False, verbose_name='Название')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время завершения')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
    ]
