# Generated by Django 4.2.16 on 2024-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_schedule', '0002_alter_rule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(choices=[('Будни', 'Будни'), ('Выходные', 'Выходные'), ('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], help_text='\nПравила на конкретные дни недели главнее чем правила на будни или выходные\n', max_length=15, primary_key=True, serialize=False, verbose_name='Название'),
        ),
    ]
