# Generated by Django 4.2.16 on 2024-09-23 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('working_schedule', '0003_alter_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='lunch_break_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время завершения обеденнего перерыва'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='end_time',
            field=models.TimeField(verbose_name='Время завершения рабочего дня'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала рабочего дня'),
        ),
    ]
