# Generated by Django 4.2.16 on 2024-09-23 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('working_schedule', '0004_rule_lunch_break_time_alter_rule_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='end_time',
            new_name='day_end_time',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='start_time',
            new_name='day_start_time',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='lunch_break_time',
            new_name='lunch_break_end_time',
        ),
        migrations.AddField(
            model_name='rule',
            name='enable_lunch_break',
            field=models.BooleanField(default=True, verbose_name='Есть ли обеденный перерыв'),
        ),
        migrations.AddField(
            model_name='rule',
            name='lunch_break_start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала обеденнего перерыва'),
            preserve_default=False,
        ),
    ]
