# Generated by Django 4.2.16 on 2024-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_schedule', '0005_rename_end_time_rule_day_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_works',
            field=models.BooleanField(default=True, verbose_name='Работает ли в эти дни'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='day_end_time',
            field=models.TimeField(help_text='По умолчанию 18:00', verbose_name='Время завершения рабочего дня'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='day_start_time',
            field=models.TimeField(help_text='По умолчанию 8:00', verbose_name='Время начала рабочего дня'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='lunch_break_end_time',
            field=models.TimeField(help_text='По умолчанию 14:00', verbose_name='Время завершения обеденнего перерыва'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='lunch_break_start_time',
            field=models.TimeField(help_text='По умолчанию 12:00', verbose_name='Время начала обеденнего перерыва'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(choices=[('Будни', 'Будни'), ('Выходные', 'Выходные'), ('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], help_text='\nПравила на конкретные дни недели главнее чем правила на будни или выходные,\nпо умолчанию по выходным не работает\n', max_length=15, primary_key=True, serialize=False, verbose_name='Название'),
        ),
    ]
