# Generated by Django 4.2.16 on 2024-09-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_schedule', '0006_rule_is_works_alter_rule_day_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='day_end_time',
            field=models.TimeField(blank=True, help_text='По умолчанию 18:00', null=True, verbose_name='Время завершения рабочего дня'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='day_start_time',
            field=models.TimeField(blank=True, help_text='По умолчанию 8:00', null=True, verbose_name='Время начала рабочего дня'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='lunch_break_end_time',
            field=models.TimeField(blank=True, help_text='По умолчанию 14:00', null=True, verbose_name='Время завершения обеденнего перерыва'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='lunch_break_start_time',
            field=models.TimeField(blank=True, help_text='По умолчанию 12:00', null=True, verbose_name='Время начала обеденнего перерыва'),
        ),
    ]
